/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CalculadoraTest {
    @Test
    public void testSuma() {
        int esperado = 5;
        int resultado = Calculadora.suma(3, 2);
        assertEquals(esperado, resultado);
    }
    
    @Test
    public void testResta() {
        int esperado = 1;
        int resultado = Calculadora.resta(3, 2);
        assertEquals(esperado, resultado);
    }
}
